pipeline {

  agent any 

  environment {
    S3bucket_name = 'houzez.app'
  }
  stages {
    stage('Sonar Cloud') {
      environment {
        SCANNER_HOME = tool 'SonarQubeScanner'
        ORGANIZATION = "zhangrunqing6599"
        PROJECT_NAME = "zhangrunqing6599_houzez-app"
      }
      steps {
        withSonarQubeEnv(installationName: 'SonarCloudJenkins', credentialsId: 'SonarCloudJenkinsToken') {
        sh '''$SCANNER_HOME/bin/sonar-scanner -Dsonar.organization=$ORGANIZATION \
        -Dsonar.java.binaries=build/classes/java/ \
        -Dsonar.projectKey=$PROJECT_NAME \
        -Dsonar.sources=.'''
        }
      }
    }
    stage('Install Packages') {
      steps {
        sh 'npm install'
      }
    }
    stage('build') {
      steps {
        sh 'echo "building ..."'
        sh 'npm run build'
      }
    }
    stage('Test') {
      steps {
        sh 'echo "Testing ..."'
        sh 'npm run test-c'
      }
    }
    stage('Upload') {
        steps {
            echo 'Deploying to AWS s3 bucket.'
            withAWS(region:'ap-southeast-2',credentials:'houzez_app') {
                sh 'aws s3 sync /var/lib/jenkins/workspace/houzez_app_frontend_cicid s3://houzez.app/ --exclude "node_modules/*"'
                // s3Delete(bucket:"houzez.app", path:'');
                // s3Upload(bucket:"houzez.app", includePathPattern:'**/*');
            }
        };
    }
  }    
    post {
        always {
            cleanWs()
            dir("${env.WORKSPACE}@tmp") {
              deleteDir()
            }
            dir("${env.WORKSPACE}@script") {
              deleteDir()
            }
            dir("${env.WORKSPACE}@script@tmp") {
              deleteDir()
            }
            // sh "docker rmi ${base_imagename}"
            // sh "docker rmi ${api_imagename}"
            // sh "docker rmi ${auth_imagename}"
        }
    }
}
